-- Voeg ledenlijst-kolommen toe aan winkels tabel
alter table winkels
  add column if not exists lidnr_drg text,
  add column if not exists cbnr text,
  add column if not exists geblokkeerd text,
  add column if not exists provincie text,
  add column if not exists contactpersoon text,
  add column if not exists telefoon text,
  add column if not exists email text,
  add column if not exists email_administratie text,
  add column if not exists website text,
  add column if not exists iban text,
  add column if not exists btw_nummer text,
  add column if not exists kvk text,
  add column if not exists gln text,
  add column if not exists regio_manager text,
  add column if not exists formule text,
  add column if not exists aangesloten_sinds text,
  add column if not exists bike_totaal_nieuw_start text,
  add column if not exists bike_totaal_nieuw_eind text,
  add column if not exists vvo_m2 text,
  add column if not exists deelname_centraal_betalen text,
  add column if not exists cm_fietsen_deelname text,
  add column if not exists cm_fietsen_instroom text,
  add column if not exists cm_fietsen_uitstroom text,
  add column if not exists kassasysteem text,
  add column if not exists laatste_contract text,
  add column if not exists jaarcijfers text,
  add column if not exists sales_channels_qv text,
  add column if not exists accountant text,
  add column if not exists startdatum_servicepas_drs text,
  add column if not exists einddatum_servicepas_drs text,
  add column if not exists webshoporders_naar_kassa text,
  add column if not exists startdatum_lease text,
  add column if not exists einddatum_lease text,
  add column if not exists deelname_servicepas_drs text,
  add column if not exists deelname_lease text;

-- Unieke index op lidnummer voor upsert (als die er nog niet is)
create unique index if not exists winkels_lidnummer_unique on winkels(lidnummer) where lidnummer is not null;
